---
system:
  mode: 1 # PULL (clients must request to fetch/receive payloads), PUSH (payloads will be forwarded when sent/posted)

database:
  use_db: true # Whether or not to use in-memory storage of payloads (via Redis)
  db_address: 127.0.0.1
  db_port: 5050
  db_num: 0