// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nsb.proto
// Protobuf C++ Version: 5.29.3

#include "nsb.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nsb {

inline constexpr nsbm_Metadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        addr_type_{static_cast< ::nsb::nsbm_Metadata_AddressType >(0)},
        payload_size_{0},
        src_{},
        dest_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR nsbm_Metadata::nsbm_Metadata(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct nsbm_MetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR nsbm_MetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~nsbm_MetadataDefaultTypeInternal() {}
  union {
    nsbm_Metadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 nsbm_MetadataDefaultTypeInternal _nsbm_Metadata_default_instance_;

inline constexpr nsbm_Manifest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        op_{static_cast< ::nsb::nsbm_Manifest_Operation >(0)},
        og_{static_cast< ::nsb::nsbm_Manifest_Originator >(0)},
        code_{static_cast< ::nsb::nsbm_Manifest_OpCode >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR nsbm_Manifest::nsbm_Manifest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct nsbm_ManifestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR nsbm_ManifestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~nsbm_ManifestDefaultTypeInternal() {}
  union {
    nsbm_Manifest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 nsbm_ManifestDefaultTypeInternal _nsbm_Manifest_default_instance_;

inline constexpr nsbm::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        manifest_{nullptr},
        metadata_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR nsbm::nsbm(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct nsbmDefaultTypeInternal {
  PROTOBUF_CONSTEXPR nsbmDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~nsbmDefaultTypeInternal() {}
  union {
    nsbm _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 nsbmDefaultTypeInternal _nsbm_default_instance_;
}  // namespace nsb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_nsb_2eproto[4];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_nsb_2eproto = nullptr;
const ::uint32_t
    TableStruct_nsb_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Manifest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Manifest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Manifest, _impl_.op_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Manifest, _impl_.og_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Manifest, _impl_.code_),
        0,
        1,
        2,
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_.addr_type_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_.payload_size_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_.src_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_.dest_),
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        1,
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm, _impl_.manifest_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm, _impl_.metadata_),
        PROTOBUF_FIELD_OFFSET(::nsb::nsbm, _impl_.payload_),
        1,
        2,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::nsb::nsbm_Manifest)},
        {14, 30, -1, sizeof(::nsb::nsbm_Metadata)},
        {36, 47, -1, sizeof(::nsb::nsbm)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::nsb::_nsbm_Manifest_default_instance_._instance,
    &::nsb::_nsbm_Metadata_default_instance_._instance,
    &::nsb::_nsbm_default_instance_._instance,
};
const char descriptor_table_protodef_nsb_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tnsb.proto\022\003nsb\"\365\005\n\004nsbm\022$\n\010manifest\030\001 "
    "\001(\0132\022.nsb.nsbm.Manifest\022$\n\010metadata\030\002 \001("
    "\0132\022.nsb.nsbm.Metadata\022\017\n\007payload\030\003 \001(\014\032\273"
    "\003\n\010Manifest\022(\n\002op\030\001 \001(\0162\034.nsb.nsbm.Manif"
    "est.Operation\022)\n\002og\030\002 \001(\0162\035.nsb.nsbm.Man"
    "ifest.Originator\022\'\n\004code\030\003 \001(\0162\031.nsb.nsb"
    "m.Manifest.OpCode\"b\n\tOperation\022\010\n\004PING\020\000"
    "\022\010\n\004INIT\020\001\022\010\n\004SEND\020\002\022\t\n\005FETCH\020\003\022\010\n\004POST\020"
    "\004\022\013\n\007RECEIVE\020\005\022\013\n\007FORWARD\020\006\022\010\n\004EXIT\020\007\"8\n"
    "\nOriginator\022\n\n\006DAEMON\020\000\022\016\n\nAPP_CLIENT\020\001\022"
    "\016\n\nSIM_CLIENT\020\002\"\222\001\n\006OpCode\022\013\n\007SUCCESS\020\000\022"
    "\013\n\007FAILURE\020\001\022\022\n\016CLIENT_REQUEST\020\002\022\023\n\017DAEM"
    "ON_RESPONSE\020\003\022\023\n\017IMPLICIT_TARGET\020\004\022\023\n\017EX"
    "PLICIT_TARGET\020\005\022\013\n\007MESSAGE\020\006\022\016\n\nNO_MESSA"
    "GE\020\007\032\321\001\n\010Metadata\0221\n\taddr_type\030\001 \001(\0162\036.n"
    "sb.nsbm.Metadata.AddressType\022\020\n\006src_id\030\002"
    " \001(\tH\000\022\022\n\010src_addr\030\003 \001(\007H\000\022\021\n\007dest_id\030\004 "
    "\001(\tH\001\022\023\n\tdest_addr\030\005 \001(\007H\001\022\024\n\014payload_si"
    "ze\030\006 \001(\005\"\037\n\013AddressType\022\007\n\003INT\020\000\022\007\n\003STR\020"
    "\001B\005\n\003srcB\006\n\004destb\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_nsb_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nsb_2eproto = {
    false,
    false,
    789,
    descriptor_table_protodef_nsb_2eproto,
    "nsb.proto",
    &descriptor_table_nsb_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_nsb_2eproto::offsets,
    file_level_enum_descriptors_nsb_2eproto,
    file_level_service_descriptors_nsb_2eproto,
};
namespace nsb {
const ::google::protobuf::EnumDescriptor* nsbm_Manifest_Operation_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nsb_2eproto);
  return file_level_enum_descriptors_nsb_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t nsbm_Manifest_Operation_internal_data_[] = {
    524288u, 0u, };
bool nsbm_Manifest_Operation_IsValid(int value) {
  return 0 <= value && value <= 7;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr nsbm_Manifest_Operation nsbm_Manifest::PING;
constexpr nsbm_Manifest_Operation nsbm_Manifest::INIT;
constexpr nsbm_Manifest_Operation nsbm_Manifest::SEND;
constexpr nsbm_Manifest_Operation nsbm_Manifest::FETCH;
constexpr nsbm_Manifest_Operation nsbm_Manifest::POST;
constexpr nsbm_Manifest_Operation nsbm_Manifest::RECEIVE;
constexpr nsbm_Manifest_Operation nsbm_Manifest::FORWARD;
constexpr nsbm_Manifest_Operation nsbm_Manifest::EXIT;
constexpr nsbm_Manifest_Operation nsbm_Manifest::Operation_MIN;
constexpr nsbm_Manifest_Operation nsbm_Manifest::Operation_MAX;
constexpr int nsbm_Manifest::Operation_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* nsbm_Manifest_Originator_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nsb_2eproto);
  return file_level_enum_descriptors_nsb_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t nsbm_Manifest_Originator_internal_data_[] = {
    196608u, 0u, };
bool nsbm_Manifest_Originator_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr nsbm_Manifest_Originator nsbm_Manifest::DAEMON;
constexpr nsbm_Manifest_Originator nsbm_Manifest::APP_CLIENT;
constexpr nsbm_Manifest_Originator nsbm_Manifest::SIM_CLIENT;
constexpr nsbm_Manifest_Originator nsbm_Manifest::Originator_MIN;
constexpr nsbm_Manifest_Originator nsbm_Manifest::Originator_MAX;
constexpr int nsbm_Manifest::Originator_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* nsbm_Manifest_OpCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nsb_2eproto);
  return file_level_enum_descriptors_nsb_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t nsbm_Manifest_OpCode_internal_data_[] = {
    524288u, 0u, };
bool nsbm_Manifest_OpCode_IsValid(int value) {
  return 0 <= value && value <= 7;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr nsbm_Manifest_OpCode nsbm_Manifest::SUCCESS;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::FAILURE;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::CLIENT_REQUEST;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::DAEMON_RESPONSE;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::IMPLICIT_TARGET;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::EXPLICIT_TARGET;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::MESSAGE;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::NO_MESSAGE;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::OpCode_MIN;
constexpr nsbm_Manifest_OpCode nsbm_Manifest::OpCode_MAX;
constexpr int nsbm_Manifest::OpCode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* nsbm_Metadata_AddressType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nsb_2eproto);
  return file_level_enum_descriptors_nsb_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t nsbm_Metadata_AddressType_internal_data_[] = {
    131072u, 0u, };
bool nsbm_Metadata_AddressType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr nsbm_Metadata_AddressType nsbm_Metadata::INT;
constexpr nsbm_Metadata_AddressType nsbm_Metadata::STR;
constexpr nsbm_Metadata_AddressType nsbm_Metadata::AddressType_MIN;
constexpr nsbm_Metadata_AddressType nsbm_Metadata::AddressType_MAX;
constexpr int nsbm_Metadata::AddressType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class nsbm_Manifest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<nsbm_Manifest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_._has_bits_);
};

nsbm_Manifest::nsbm_Manifest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nsb.nsbm.Manifest)
}
nsbm_Manifest::nsbm_Manifest(
    ::google::protobuf::Arena* arena, const nsbm_Manifest& from)
    : nsbm_Manifest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE nsbm_Manifest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void nsbm_Manifest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_),
           0,
           offsetof(Impl_, code_) -
               offsetof(Impl_, op_) +
               sizeof(Impl_::code_));
}
nsbm_Manifest::~nsbm_Manifest() {
  // @@protoc_insertion_point(destructor:nsb.nsbm.Manifest)
  SharedDtor(*this);
}
inline void nsbm_Manifest::SharedDtor(MessageLite& self) {
  nsbm_Manifest& this_ = static_cast<nsbm_Manifest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* nsbm_Manifest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) nsbm_Manifest(arena);
}
constexpr auto nsbm_Manifest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(nsbm_Manifest),
                                            alignof(nsbm_Manifest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull nsbm_Manifest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_nsbm_Manifest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &nsbm_Manifest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<nsbm_Manifest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &nsbm_Manifest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<nsbm_Manifest>(), &nsbm_Manifest::ByteSizeLong,
            &nsbm_Manifest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_._cached_size_),
        false,
    },
    &nsbm_Manifest::kDescriptorMethods,
    &descriptor_table_nsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* nsbm_Manifest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> nsbm_Manifest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nsb::nsbm_Manifest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .nsb.nsbm.Manifest.Operation op = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(nsbm_Manifest, _impl_.op_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.op_)}},
    // .nsb.nsbm.Manifest.Originator og = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(nsbm_Manifest, _impl_.og_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.og_)}},
    // .nsb.nsbm.Manifest.OpCode code = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(nsbm_Manifest, _impl_.code_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nsb.nsbm.Manifest.Operation op = 1;
    {PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.op_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .nsb.nsbm.Manifest.Originator og = 2;
    {PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.og_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .nsb.nsbm.Manifest.OpCode code = 3;
    {PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.code_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void nsbm_Manifest::Clear() {
// @@protoc_insertion_point(message_clear_start:nsb.nsbm.Manifest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.op_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.code_) -
        reinterpret_cast<char*>(&_impl_.op_)) + sizeof(_impl_.code_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* nsbm_Manifest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const nsbm_Manifest& this_ = static_cast<const nsbm_Manifest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* nsbm_Manifest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const nsbm_Manifest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nsb.nsbm.Manifest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .nsb.nsbm.Manifest.Operation op = 1;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_op(), target);
          }

          // .nsb.nsbm.Manifest.Originator og = 2;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_og(), target);
          }

          // .nsb.nsbm.Manifest.OpCode code = 3;
          if (cached_has_bits & 0x00000004u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_code(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nsb.nsbm.Manifest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t nsbm_Manifest::ByteSizeLong(const MessageLite& base) {
          const nsbm_Manifest& this_ = static_cast<const nsbm_Manifest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t nsbm_Manifest::ByteSizeLong() const {
          const nsbm_Manifest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nsb.nsbm.Manifest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // .nsb.nsbm.Manifest.Operation op = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_op());
            }
            // .nsb.nsbm.Manifest.Originator og = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_og());
            }
            // .nsb.nsbm.Manifest.OpCode code = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void nsbm_Manifest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<nsbm_Manifest*>(&to_msg);
  auto& from = static_cast<const nsbm_Manifest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nsb.nsbm.Manifest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.op_ = from._impl_.op_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.og_ = from._impl_.og_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.code_ = from._impl_.code_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void nsbm_Manifest::CopyFrom(const nsbm_Manifest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nsb.nsbm.Manifest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void nsbm_Manifest::InternalSwap(nsbm_Manifest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.code_)
      + sizeof(nsbm_Manifest::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(nsbm_Manifest, _impl_.op_)>(
          reinterpret_cast<char*>(&_impl_.op_),
          reinterpret_cast<char*>(&other->_impl_.op_));
}

::google::protobuf::Metadata nsbm_Manifest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class nsbm_Metadata::_Internal {
 public:
  using HasBits =
      decltype(std::declval<nsbm_Metadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::nsb::nsbm_Metadata, _impl_._oneof_case_);
};

nsbm_Metadata::nsbm_Metadata(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nsb.nsbm.Metadata)
}
inline PROTOBUF_NDEBUG_INLINE nsbm_Metadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nsb::nsbm_Metadata& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        src_{},
        dest_{},
        _oneof_case_{from._oneof_case_[0], from._oneof_case_[1]} {}

nsbm_Metadata::nsbm_Metadata(
    ::google::protobuf::Arena* arena,
    const nsbm_Metadata& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  nsbm_Metadata* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, addr_type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, addr_type_),
           offsetof(Impl_, payload_size_) -
               offsetof(Impl_, addr_type_) +
               sizeof(Impl_::payload_size_));
  switch (src_case()) {
    case SRC_NOT_SET:
      break;
      case kSrcId:
        new (&_impl_.src_.src_id_) decltype(_impl_.src_.src_id_){arena, from._impl_.src_.src_id_};
        break;
      case kSrcAddr:
        _impl_.src_.src_addr_ = from._impl_.src_.src_addr_;
        break;
  }
  switch (dest_case()) {
    case DEST_NOT_SET:
      break;
      case kDestId:
        new (&_impl_.dest_.dest_id_) decltype(_impl_.dest_.dest_id_){arena, from._impl_.dest_.dest_id_};
        break;
      case kDestAddr:
        _impl_.dest_.dest_addr_ = from._impl_.dest_.dest_addr_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:nsb.nsbm.Metadata)
}
inline PROTOBUF_NDEBUG_INLINE nsbm_Metadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        src_{},
        dest_{},
        _oneof_case_{} {}

inline void nsbm_Metadata::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, addr_type_),
           0,
           offsetof(Impl_, payload_size_) -
               offsetof(Impl_, addr_type_) +
               sizeof(Impl_::payload_size_));
}
nsbm_Metadata::~nsbm_Metadata() {
  // @@protoc_insertion_point(destructor:nsb.nsbm.Metadata)
  SharedDtor(*this);
}
inline void nsbm_Metadata::SharedDtor(MessageLite& self) {
  nsbm_Metadata& this_ = static_cast<nsbm_Metadata&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_src()) {
    this_.clear_src();
  }
  if (this_.has_dest()) {
    this_.clear_dest();
  }
  this_._impl_.~Impl_();
}

void nsbm_Metadata::clear_src() {
// @@protoc_insertion_point(one_of_clear_start:nsb.nsbm.Metadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (src_case()) {
    case kSrcId: {
      _impl_.src_.src_id_.Destroy();
      break;
    }
    case kSrcAddr: {
      // No need to clear
      break;
    }
    case SRC_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SRC_NOT_SET;
}

void nsbm_Metadata::clear_dest() {
// @@protoc_insertion_point(one_of_clear_start:nsb.nsbm.Metadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (dest_case()) {
    case kDestId: {
      _impl_.dest_.dest_id_.Destroy();
      break;
    }
    case kDestAddr: {
      // No need to clear
      break;
    }
    case DEST_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[1] = DEST_NOT_SET;
}


inline void* nsbm_Metadata::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) nsbm_Metadata(arena);
}
constexpr auto nsbm_Metadata::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(nsbm_Metadata),
                                            alignof(nsbm_Metadata));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull nsbm_Metadata::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_nsbm_Metadata_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &nsbm_Metadata::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<nsbm_Metadata>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &nsbm_Metadata::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<nsbm_Metadata>(), &nsbm_Metadata::ByteSizeLong,
            &nsbm_Metadata::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_._cached_size_),
        false,
    },
    &nsbm_Metadata::kDescriptorMethods,
    &descriptor_table_nsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* nsbm_Metadata::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 6, 0, 39, 2> nsbm_Metadata::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_._has_bits_),
    0, // no _extensions_
    6, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nsb::nsbm_Metadata>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 payload_size = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(nsbm_Metadata, _impl_.payload_size_), 1>(),
     {48, 1, 0, PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.payload_size_)}},
    // .nsb.nsbm.Metadata.AddressType addr_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(nsbm_Metadata, _impl_.addr_type_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.addr_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nsb.nsbm.Metadata.AddressType addr_type = 1;
    {PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.addr_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string src_id = 2;
    {PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.src_.src_id_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // fixed32 src_addr = 3;
    {PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.src_.src_addr_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kFixed32)},
    // string dest_id = 4;
    {PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.dest_.dest_id_), _Internal::kOneofCaseOffset + 4, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // fixed32 dest_addr = 5;
    {PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.dest_.dest_addr_), _Internal::kOneofCaseOffset + 4, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kFixed32)},
    // int32 payload_size = 6;
    {PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.payload_size_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\0\6\0\7\0\0\0"
    "nsb.nsbm.Metadata"
    "src_id"
    "dest_id"
  }},
};

PROTOBUF_NOINLINE void nsbm_Metadata::Clear() {
// @@protoc_insertion_point(message_clear_start:nsb.nsbm.Metadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.addr_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.payload_size_) -
        reinterpret_cast<char*>(&_impl_.addr_type_)) + sizeof(_impl_.payload_size_));
  }
  clear_src();
  clear_dest();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* nsbm_Metadata::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const nsbm_Metadata& this_ = static_cast<const nsbm_Metadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* nsbm_Metadata::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const nsbm_Metadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nsb.nsbm.Metadata)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .nsb.nsbm.Metadata.AddressType addr_type = 1;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_addr_type(), target);
          }

          switch (this_.src_case()) {
            case kSrcId: {
              const std::string& _s = this_._internal_src_id();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nsb.nsbm.Metadata.src_id");
              target = stream->WriteStringMaybeAliased(2, _s, target);
              break;
            }
            case kSrcAddr: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                  3, this_._internal_src_addr(), target);
              break;
            }
            default:
              break;
          }
          switch (this_.dest_case()) {
            case kDestId: {
              const std::string& _s = this_._internal_dest_id();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nsb.nsbm.Metadata.dest_id");
              target = stream->WriteStringMaybeAliased(4, _s, target);
              break;
            }
            case kDestAddr: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                  5, this_._internal_dest_addr(), target);
              break;
            }
            default:
              break;
          }
          // int32 payload_size = 6;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_payload_size(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nsb.nsbm.Metadata)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t nsbm_Metadata::ByteSizeLong(const MessageLite& base) {
          const nsbm_Metadata& this_ = static_cast<const nsbm_Metadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t nsbm_Metadata::ByteSizeLong() const {
          const nsbm_Metadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nsb.nsbm.Metadata)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .nsb.nsbm.Metadata.AddressType addr_type = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_addr_type());
            }
            // int32 payload_size = 6;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_payload_size());
            }
          }
          switch (this_.src_case()) {
            // string src_id = 2;
            case kSrcId: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_src_id());
              break;
            }
            // fixed32 src_addr = 3;
            case kSrcAddr: {
              total_size += 5;
              break;
            }
            case SRC_NOT_SET: {
              break;
            }
          }
          switch (this_.dest_case()) {
            // string dest_id = 4;
            case kDestId: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_dest_id());
              break;
            }
            // fixed32 dest_addr = 5;
            case kDestAddr: {
              total_size += 5;
              break;
            }
            case DEST_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void nsbm_Metadata::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<nsbm_Metadata*>(&to_msg);
  auto& from = static_cast<const nsbm_Metadata&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nsb.nsbm.Metadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.addr_type_ = from._impl_.addr_type_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.payload_size_ = from._impl_.payload_size_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_src();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kSrcId: {
        if (oneof_needs_init) {
          _this->_impl_.src_.src_id_.InitDefault();
        }
        _this->_impl_.src_.src_id_.Set(from._internal_src_id(), arena);
        break;
      }
      case kSrcAddr: {
        _this->_impl_.src_.src_addr_ = from._impl_.src_.src_addr_;
        break;
      }
      case SRC_NOT_SET:
        break;
    }
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[1]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[1];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_dest();
      }
      _this->_impl_._oneof_case_[1] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kDestId: {
        if (oneof_needs_init) {
          _this->_impl_.dest_.dest_id_.InitDefault();
        }
        _this->_impl_.dest_.dest_id_.Set(from._internal_dest_id(), arena);
        break;
      }
      case kDestAddr: {
        _this->_impl_.dest_.dest_addr_ = from._impl_.dest_.dest_addr_;
        break;
      }
      case DEST_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void nsbm_Metadata::CopyFrom(const nsbm_Metadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nsb.nsbm.Metadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void nsbm_Metadata::InternalSwap(nsbm_Metadata* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.payload_size_)
      + sizeof(nsbm_Metadata::_impl_.payload_size_)
      - PROTOBUF_FIELD_OFFSET(nsbm_Metadata, _impl_.addr_type_)>(
          reinterpret_cast<char*>(&_impl_.addr_type_),
          reinterpret_cast<char*>(&other->_impl_.addr_type_));
  swap(_impl_.src_, other->_impl_.src_);
  swap(_impl_.dest_, other->_impl_.dest_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
  swap(_impl_._oneof_case_[1], other->_impl_._oneof_case_[1]);
}

::google::protobuf::Metadata nsbm_Metadata::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class nsbm::_Internal {
 public:
  using HasBits =
      decltype(std::declval<nsbm>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(nsbm, _impl_._has_bits_);
};

nsbm::nsbm(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nsb.nsbm)
}
inline PROTOBUF_NDEBUG_INLINE nsbm::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nsb::nsbm& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_(arena, from.payload_) {}

nsbm::nsbm(
    ::google::protobuf::Arena* arena,
    const nsbm& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  nsbm* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.manifest_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::nsb::nsbm_Manifest>(
                              arena, *from._impl_.manifest_)
                        : nullptr;
  _impl_.metadata_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::nsb::nsbm_Metadata>(
                              arena, *from._impl_.metadata_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:nsb.nsbm)
}
inline PROTOBUF_NDEBUG_INLINE nsbm::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        payload_(arena) {}

inline void nsbm::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, manifest_),
           0,
           offsetof(Impl_, metadata_) -
               offsetof(Impl_, manifest_) +
               sizeof(Impl_::metadata_));
}
nsbm::~nsbm() {
  // @@protoc_insertion_point(destructor:nsb.nsbm)
  SharedDtor(*this);
}
inline void nsbm::SharedDtor(MessageLite& self) {
  nsbm& this_ = static_cast<nsbm&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  delete this_._impl_.manifest_;
  delete this_._impl_.metadata_;
  this_._impl_.~Impl_();
}

inline void* nsbm::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) nsbm(arena);
}
constexpr auto nsbm::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(nsbm),
                                            alignof(nsbm));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull nsbm::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_nsbm_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &nsbm::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<nsbm>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &nsbm::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<nsbm>(), &nsbm::ByteSizeLong,
            &nsbm::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(nsbm, _impl_._cached_size_),
        false,
    },
    &nsbm::kDescriptorMethods,
    &descriptor_table_nsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* nsbm::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> nsbm::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(nsbm, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nsb::nsbm>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .nsb.nsbm.Manifest manifest = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0, PROTOBUF_FIELD_OFFSET(nsbm, _impl_.manifest_)}},
    // .nsb.nsbm.Metadata metadata = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 2, 1, PROTOBUF_FIELD_OFFSET(nsbm, _impl_.metadata_)}},
    // bytes payload = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(nsbm, _impl_.payload_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nsb.nsbm.Manifest manifest = 1;
    {PROTOBUF_FIELD_OFFSET(nsbm, _impl_.manifest_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .nsb.nsbm.Metadata metadata = 2;
    {PROTOBUF_FIELD_OFFSET(nsbm, _impl_.metadata_), _Internal::kHasBitsOffset + 2, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes payload = 3;
    {PROTOBUF_FIELD_OFFSET(nsbm, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::nsb::nsbm_Manifest>()},
    {::_pbi::TcParser::GetTable<::nsb::nsbm_Metadata>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void nsbm::Clear() {
// @@protoc_insertion_point(message_clear_start:nsb.nsbm)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.payload_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.manifest_ != nullptr);
      _impl_.manifest_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.metadata_ != nullptr);
      _impl_.metadata_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* nsbm::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const nsbm& this_ = static_cast<const nsbm&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* nsbm::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const nsbm& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nsb.nsbm)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .nsb.nsbm.Manifest manifest = 1;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.manifest_, this_._impl_.manifest_->GetCachedSize(), target,
                stream);
          }

          // .nsb.nsbm.Metadata metadata = 2;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.metadata_, this_._impl_.metadata_->GetCachedSize(), target,
                stream);
          }

          // bytes payload = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_payload();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nsb.nsbm)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t nsbm::ByteSizeLong(const MessageLite& base) {
          const nsbm& this_ = static_cast<const nsbm&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t nsbm::ByteSizeLong() const {
          const nsbm& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nsb.nsbm)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // bytes payload = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_payload());
            }
            // .nsb.nsbm.Manifest manifest = 1;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.manifest_);
            }
            // .nsb.nsbm.Metadata metadata = 2;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.metadata_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void nsbm::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<nsbm*>(&to_msg);
  auto& from = static_cast<const nsbm&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nsb.nsbm)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_payload(from._internal_payload());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.manifest_ != nullptr);
      if (_this->_impl_.manifest_ == nullptr) {
        _this->_impl_.manifest_ =
            ::google::protobuf::Message::CopyConstruct<::nsb::nsbm_Manifest>(arena, *from._impl_.manifest_);
      } else {
        _this->_impl_.manifest_->MergeFrom(*from._impl_.manifest_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.metadata_ != nullptr);
      if (_this->_impl_.metadata_ == nullptr) {
        _this->_impl_.metadata_ =
            ::google::protobuf::Message::CopyConstruct<::nsb::nsbm_Metadata>(arena, *from._impl_.metadata_);
      } else {
        _this->_impl_.metadata_->MergeFrom(*from._impl_.metadata_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void nsbm::CopyFrom(const nsbm& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nsb.nsbm)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void nsbm::InternalSwap(nsbm* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(nsbm, _impl_.metadata_)
      + sizeof(nsbm::_impl_.metadata_)
      - PROTOBUF_FIELD_OFFSET(nsbm, _impl_.manifest_)>(
          reinterpret_cast<char*>(&_impl_.manifest_),
          reinterpret_cast<char*>(&other->_impl_.manifest_));
}

::google::protobuf::Metadata nsbm::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nsb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_nsb_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
