# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nsb.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'nsb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnsb.proto\x12\x03nsb\"\xae\x05\n\x04nsbm\x12$\n\x08manifest\x18\x01 \x02(\x0b\x32\x12.nsb.nsbm.Manifest\x12$\n\x08metadata\x18\x02 \x01(\x0b\x32\x12.nsb.nsbm.Metadata\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\x1a\x82\x03\n\x08Manifest\x12(\n\x02op\x18\x01 \x02(\x0e\x32\x1c.nsb.nsbm.Manifest.Operation\x12)\n\x02og\x18\x02 \x02(\x0e\x32\x1d.nsb.nsbm.Manifest.Originator\x12\'\n\x04\x63ode\x18\x03 \x01(\x0e\x32\x19.nsb.nsbm.Manifest.OpCode\")\n\tOperation\x12\x08\n\x04PING\x10\x01\x12\x08\n\x04INIT\x10\x02\x12\x08\n\x04\x45XIT\x10\x08\"8\n\nOriginator\x12\n\n\x06\x44\x41\x45MON\x10\x00\x12\x0e\n\nAPP_CLIENT\x10\x01\x12\x0e\n\nSIM_CLIENT\x10\x02\"\x92\x01\n\x06OpCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\x12\n\x0e\x43LIENT_REQUEST\x10\x02\x12\x13\n\x0f\x44\x41\x45MON_RESPONSE\x10\x03\x12\x13\n\x0fIMPLICIT_TARGET\x10\x04\x12\x13\n\x0f\x45XPLICIT_TARGET\x10\x05\x12\x0b\n\x07MESSAGE\x10\x06\x12\x0e\n\nNO_MESSAGE\x10\x07\x1a\xc3\x01\n\x08Metadata\x12*\n\taddr_type\x18\x01 \x02(\x0e\x32\x17.nsb.nsbm.Metadata.Type\x12\x10\n\x06src_id\x18\x02 \x01(\tH\x00\x12\x12\n\x08src_addr\x18\x03 \x01(\x07H\x00\x12\x11\n\x07\x64\x65st_id\x18\x04 \x01(\tH\x01\x12\x13\n\tdest_addr\x18\x05 \x01(\x07H\x01\x12\x14\n\x0cpayload_size\x18\x06 \x01(\x05\"\x18\n\x04Type\x12\x07\n\x03INT\x10\x00\x12\x07\n\x03STR\x10\x01\x42\x05\n\x03srcB\x06\n\x04\x64\x65st')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nsb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NSBM']._serialized_start=19
  _globals['_NSBM']._serialized_end=705
  _globals['_NSBM_MANIFEST']._serialized_start=121
  _globals['_NSBM_MANIFEST']._serialized_end=507
  _globals['_NSBM_MANIFEST_OPERATION']._serialized_start=259
  _globals['_NSBM_MANIFEST_OPERATION']._serialized_end=300
  _globals['_NSBM_MANIFEST_ORIGINATOR']._serialized_start=302
  _globals['_NSBM_MANIFEST_ORIGINATOR']._serialized_end=358
  _globals['_NSBM_MANIFEST_OPCODE']._serialized_start=361
  _globals['_NSBM_MANIFEST_OPCODE']._serialized_end=507
  _globals['_NSBM_METADATA']._serialized_start=510
  _globals['_NSBM_METADATA']._serialized_end=705
  _globals['_NSBM_METADATA_TYPE']._serialized_start=666
  _globals['_NSBM_METADATA_TYPE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
